services:
  php-fpm:
    # image: php:7.4-fpm
    image: php-school-lab
    volumes:
      - ./src:/var/www/html
    networks:
      app-network:
        ipv4_address: 10.0.0.2
  nginx:
    image: nginx:1.17.8
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      app-network:
        ipv4_address: 10.0.0.3
    links:
      - php-fpm
  mariadb:
    image: mariadb:10.4.12
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    volumes:
      - ./mariadb:/var/lib/mysql
    networks:
      app-network: 
        ipv4_address: 10.0.0.4
networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1
